FROM ubuntu:20.04
RUN apt update && apt install -y nvidia-utils-570-server ipmitool curl gpg python3-pip python3-venv
# inspired by https://docs.influxdata.com/telegraf/v1/install/#install-from-the-influxdata-repository but removed sudo
RUN curl --silent --location -O \
    https://repos.influxdata.com/influxdata-archive.key \
    && echo "943666881a1b8d9b849b74caebf02d3465d6beb716510d86a39f6c8e8dac7515  influxdata-archive.key" \
    | sha256sum -c - && cat influxdata-archive.key \
    | gpg --dearmor \
    | tee /etc/apt/trusted.gpg.d/influxdata-archive.gpg > /dev/null \
    && echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive.gpg] https://repos.influxdata.com/debian stable main' \
    | tee /etc/apt/sources.list.d/influxdata.list
RUN apt update && apt install telegraf
RUN mkdir /nadiki
WORKDIR /nadiki
COPY requirements-nadiki.txt telegraf.conf nadiki-facility-electricitymap-crawler.py nadiki-facility-zabbix-crawler.py diff.star .
RUN python3 -mvenv .
RUN bash -c "source bin/activate && pip3 install -r requirements-nadiki.txt"
CMD ["bash", "-c", "source bin/activate && /usr/bin/telegraf --config telegraf.conf"]
